# @baseUrl = https://sainthenri-basketball-drf4g9dkasfdhfa2.canadacentral-01.azurewebsites.net
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImEyYmY1MDA2LWYzNjEtNDNiYy1iZjRiLTliMDQ1ZmUxNmU3OCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImpvaG5AZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiam9obmRvZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3MzY5ODU1MjAsImlzcyI6IlNhaW50SGVucmlCYXNrZXRiYWxsIiwiYXVkIjoiU2FpbnRIZW5yaUJhc2tldGJhbGxDbGllbnQifQ.sb6QXqsvOCP47X0trTQjbudflozX7U7gpoz_jdUE09w
@userId = a2bf5006-f361-43bc-bf4b-9b045fe16e78
@adminToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIyOTlhZDEyLTRkZTItNDc1Yy1hNzc1LTcyMjJiODc0OTU5ZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHNhaW50aGVucmliYXNrZXRiYWxsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzM3NDIzODQ2LCJpc3MiOiJTYWludEhlbnJpQmFza2V0YmFsbCIsImF1ZCI6IlNhaW50SGVucmlCYXNrZXRiYWxsQ2xpZW50In0.zGDvjVmOG6Qtz1aabrU-G2jjRPotIcNIgcOTh_xLiaI
@baseUrl = https://localhost:7000
### Login
POST {{baseUrl}}/api/users/login
Accept: application/json
Content-Type: application/json

{
  "userName": "admin",
  "password": "Admin@2025"
}

### Season
POST {{baseUrl}}/api/seasons
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "startDate": "2025-07-14T10:00:00.000Z",
  "endDate": "2025-10-27T12:00:00.000Z",
  "price": 110,
  "status": 0,
  "notes": "Let's hoop"
}

### Get all seasons
GET {{baseUrl}}/api/seasons
Authorization: Bearer {{adminToken}}

### Get a season by id
@seasonId = 3d18f4a5-aa56-412e-bb5c-bf6b9bafc2fa
GET {{baseUrl}}/api/seasons/{{seasonId}}
Authorization: Bearer {{adminToken}}

### Update a season
PUT {{baseUrl}}/api/seasons/{{seasonId}}
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "startDate": "2025-06-14T10:00:00.000Z",
  "endDate": "2025-09-27T12:00:00.000Z",
  "price": 85,
  "status": 0,
  "notes": "Let's hoop"
}

### Get current season
GET {{baseUrl}}/api/seasons/current
Authorization: Bearer {{adminToken}}

### Update season
PUT {{baseUrl}}/api/seasons/{{seasonId}}
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "startDate": "2025-07-14T10:00:00",
  "endDate": "2025-10-27T12:00:00",
  "price": 100,
  "notes": "Let's have some fun on the court. Let's gooo"
}

### DELETE 
DELETE {{baseUrl}}/api/seasons/{{seasonId}}
Authorization: Bearer {{adminToken}}

### GET status
PATCH {{baseUrl}}/api/seasons/{{seasonId}}/status
Authorization: Bearer {{adminToken}}
Content-Type: application/json

0

### Register
POST {{baseUrl}}/api/seasons/{{seasonId}}/register
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{}

### unregister
DELETE {{baseUrl}}/api/seasons/{{seasonId}}/register
Authorization: Bearer {{adminToken}}

### Get seasion users
GET {{baseUrl}}/api/seasons/{{seasonId}}/users
Authorization: Bearer {{adminToken}}

###
POST https://localhost:7000/api/Seasons/3d18f4a5-aa56-412e-bb5c-bf6b9bafc2fa/register
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIyOTlhZDEyLTRkZTItNDc1Yy1hNzc1LTcyMjJiODc0OTU5ZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHNhaW50aGVucmliYXNrZXRiYWxsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzM3NDA5Nzg1LCJpc3MiOiJTYWludEhlbnJpQmFza2V0YmFsbCIsImF1ZCI6IlNhaW50SGVucmlCYXNrZXRiYWxsQ2xpZW50In0.YSVq1IiDwF-Fz7glrA9pCGsdmMWOQwdFtmEAfel5OHs