@SaintHenriBasketball.API_HostAddress = https://sainthenri-basketball-drf4g9dkasfdhfa2.canadacentral-01.azurewebsites.net

POST {{SaintHenriBasketball.API_HostAddress}}/api/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "fsawadogo",
  "email": "fsawadogo@gmail.com",
  "password": "Admin@123",
  "firstName": "Abdoul",
  "lastName": "Sawadogo"
}
### Login

POST {{SaintHenriBasketball.API_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "faycalsawadogo@gmail.com",
  "password": "Admin@1234"
}

### Me
GET {{SaintHenriBasketball.API_HostAddress}}/api/Auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImIwYjhkNmQzLTEwODItNGEyNi04NDgxLThjNWZlMDZmNDM4OSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImZzYXdhZG9nb0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZnNhd2Fkb2dvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3MzYzNzc1MTUsImlzcyI6IlNhaW50SGVucmlCYXNrZXRiYWxsIiwiYXVkIjoiU2FpbnRIZW5yaUJhc2tldGJhbGxDbGllbnQifQ.Fjavjt4h0BuVoIoGHa5NaehOdQ_iR7i0B6Jp-Sh3jLg"