@SaintHenriBasketball.API_HostAddress = http://localhost:5004

POST {{SaintHenriBasketball.API_HostAddress}}/api/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "afsawadogo",
  "email": "afaicals@gmail.com",
  "password": "Admin@2025",
  "firstName": "Abdoul",
  "lastName": "Sawadogo",
  "paymentPlan": 0
}

### Login

POST {{SaintHenriBasketball.API_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "faycalsawadogo@gmail.com",
  "password": "Kouanda75!"
}

### mark attendance
@sessionId = d0b69cde-e8e3-4277-82f1-0b789de7ccb3
POST {{SaintHenriBasketball.API_HostAddress}}/api/Attendance/sessions/{{sessionId}}
Accept: application/json
Content-Type: application/json

{
  "isAttending": true,
  "notes": "hello test"
}


###
PUT https://sainthenri-basketball-drf4g9dkasfdhfa2.canadacentral-01.azurewebsites.net/api/Sessions/5c6f097a-867f-4653-95d4-549f1fcdb054
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIyOTlhZDEyLTRkZTItNDc1Yy1hNzc1LTcyMjJiODc0OTU5ZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHNhaW50aGVucmliYXNrZXRiYWxsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzM3MjEwODIxLCJpc3MiOiJTYWludEhlbnJpQmFza2V0YmFsbCIsImF1ZCI6IlNhaW50SGVucmlCYXNrZXRiYWxsQ2xpZW50In0.I-U6mQ3O6gHYSXBwPcwUe5YZ7l5Kajf4rNlMM0H-U94
Accept: application/json
Content-Type: application/json

{
  "sessionDate": "2025-01-24T15:00:00.000Z",
  "maxCapacity": 20,
  "dropInPrice": 10,
  "status": 0,
  "startTime": "10:00",
  "endTime": "12:00",
  "location": "717 Saint-Ferdinand Street, Montreal, QC H4C 3L7"
}