@SaintHenriBasketball.API_HostAddress = http://localhost:5004

POST {{SaintHenriBasketball.API_HostAddress}}/api/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "afsawadogo",
  "email": "afaicals@gmail.com",
  "password": "Admin@2025",
  "firstName": "Abdoul",
  "lastName": "Sawadogo",
  "paymentPlan": 0
}

### Login

POST {{SaintHenriBasketball.API_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "faycalsawadogo@gmail.com",
  "password": "Kouanda75!"
}

### mark attendance
@sessionId = d0b69cde-e8e3-4277-82f1-0b789de7ccb3
POST {{SaintHenriBasketball.API_HostAddress}}/api/Attendance/sessions/{{sessionId}}
Accept: application/json
Content-Type: application/json

{
  "isAttending": true,
  "notes": "hello test"
}