namespace SaintHenriBasketball.Application.FeatureFlags;

public record FeatureFlagDefinition(string Key, string Description, string DescriptionFr, bool IsPublic = true);

/// Authoritative list of every feature flag known at compile time. Seeded on startup.
public static class FeatureFlagDefinitions
{
    public static readonly IReadOnlyList<FeatureFlagDefinition> All = new[]
    {
        // Phase 1
        new FeatureFlagDefinition(FeatureFlagKeys.CalendarSync,
            "Per-user .ics calendar feed for registered sessions.",
            "Flux de calendrier .ics personnel pour les séances inscrites."),
        new FeatureFlagDefinition(FeatureFlagKeys.AuditLogViewer,
            "Admin UI for browsing the audit log.",
            "Interface d'administration pour consulter le journal d'audit.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.Admin2fa,
            "Require TOTP two-factor authentication for admin accounts.",
            "Exiger une authentification à deux facteurs TOTP pour les comptes administrateurs.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.PwaInstall,
            "Progressive Web App install prompt and offline shell.",
            "Installation PWA et coque hors ligne."),

        // Phase 2
        new FeatureFlagDefinition(FeatureFlagKeys.QrCheckIn,
            "QR-code-based session check-in flow.",
            "Inscription à la séance via code QR."),
        new FeatureFlagDefinition(FeatureFlagKeys.StreaksBadges,
            "Attendance streaks and badge awards.",
            "Séries de présences et badges."),
        new FeatureFlagDefinition(FeatureFlagKeys.SessionFeedback,
            "Post-session NPS rating and comment.",
            "Évaluation NPS et commentaires après la séance."),
        new FeatureFlagDefinition(FeatureFlagKeys.PersonalStats,
            "Personal stats page (My SHB Year).",
            "Page des statistiques personnelles (Mon année SHB)."),
        new FeatureFlagDefinition(FeatureFlagKeys.SessionRecaps,
            "Admin-uploaded session photo recaps.",
            "Récapitulatifs photo des séances publiés par l'administrateur."),

        // Phase 3
        new FeatureFlagDefinition(FeatureFlagKeys.RecurringSessions,
            "Recurring session generator from a template.",
            "Générateur de séances récurrentes à partir d'un modèle.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.InteracReconciliation,
            "Admin dashboard for reconciling Interac payments.",
            "Tableau de bord administrateur pour rapprocher les paiements Interac.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.AdminBroadcast,
            "Admin broadcast / announcement composer.",
            "Compositeur de diffusion / annonce administrateur.",
            IsPublic: false),

        // Phase 4
        new FeatureFlagDefinition(FeatureFlagKeys.TaxReceipts,
            "Annual payment summary PDF for players (not an official tax receipt).",
            "Sommaire annuel des paiements en PDF pour les joueurs (pas un reçu fiscal officiel)."),
        new FeatureFlagDefinition(FeatureFlagKeys.Referrals,
            "Referral codes and invite-a-friend rewards.",
            "Codes de parrainage et récompenses d'invitation."),
        new FeatureFlagDefinition(FeatureFlagKeys.PromoCodes,
            "Admin-defined promo / discount codes at checkout.",
            "Codes promotionnels définis par l'administrateur au paiement."),

        // Phase 5
        new FeatureFlagDefinition(FeatureFlagKeys.Waiver,
            "Liability-waiver acceptance at registration.",
            "Acceptation de la décharge de responsabilité à l'inscription."),
        new FeatureFlagDefinition(FeatureFlagKeys.EmergencyProfile,
            "Emergency contact and medical alerts on the user profile.",
            "Contact d'urgence et alertes médicales sur le profil."),
        new FeatureFlagDefinition(FeatureFlagKeys.SmsReminders,
            "SMS session-day reminders via the configured SMS provider (Twilio or Brevo).",
            "Rappels SMS le jour de la séance via le fournisseur SMS configuré (Twilio ou Brevo)."),
        new FeatureFlagDefinition(FeatureFlagKeys.PublicSchedule,
            "Public anonymous schedule / upcoming-sessions page.",
            "Page publique anonyme du calendrier / séances à venir."),
        new FeatureFlagDefinition(FeatureFlagKeys.InAppNotifications,
            "Bell icon + in-app notification center.",
            "Icône cloche et centre de notifications dans l'application."),

        // Phase 7
        new FeatureFlagDefinition(FeatureFlagKeys.Gallery,
            "Public /gallery page mirroring the Instagram feed.",
            "Page publique /galerie miroir du fil Instagram."),

        // Phase 8
        new FeatureFlagDefinition(FeatureFlagKeys.SessionAttendees,
            "Dashboard list of players who confirmed attendance (first name and last initial).",
            "Liste au tableau de bord des joueurs ayant confirmé leur présence (prénom et initiale)."),
        new FeatureFlagDefinition(FeatureFlagKeys.SeasonPaymentReminders,
            "Remind season players with unpaid fees before they confirm attendance.",
            "Rappeler les frais de saison impayés avant la confirmation de présence."),
        new FeatureFlagDefinition(FeatureFlagKeys.InteracReviewQueue,
            "Shortcut on the payments page to the Interac transfers waiting for verification (the queue itself is Payment reconciliation).",
            "Raccourci sur la page des paiements vers les virements Interac à vérifier (la file elle-même est le rapprochement des paiements).",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.SeasonCardPayments,
            "Season players can pay the season fee by card (Stripe Checkout) in the app.",
            "Les joueurs de saison peuvent payer les frais de saison par carte (Stripe Checkout) dans l'application."),

        // Phase 9 — Admin audit: new admin tools
        new FeatureFlagDefinition(FeatureFlagKeys.OutstandingBalances,
            "Admin list of who owes what (season fees, drop-ins, transfers awaiting review) with reminders and a reminder history.",
            "Liste des soldes impayés (frais de saison, séances, virements à vérifier) avec rappels et historique des rappels.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.CourtAttendance,
            "Phone roster per session to mark attended, no-show or walk-in, with payment status and no-show stats.",
            "Liste de présence mobile par séance : présent, absent ou sans inscription, avec l’état du paiement et les absences.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.TreasurerReport,
            "Treasurer report: collected vs outstanding by month and season, Interac vs card, promo and credit cost, refunds, audited CSV export.",
            "Rapport du trésorier : perçu et à percevoir par mois et saison, Interac ou carte, coût des promos et crédits, remboursements, export CSV audité.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.PlayerTimeline,
            "One timeline on the player page: payments, credits, referrals, waiver, attendance, messages and notes.",
            "Chronologie unique sur la fiche du joueur : paiements, crédits, parrainages, décharge, présences, messages et notes.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.SeasonRollover,
            "Copy a season (dates, fee, Saturday sessions) into a draft and invite season players to renew.",
            "Copier une saison (dates, frais, séances du samedi) en brouillon et inviter les joueurs de saison à renouveler.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.WaitlistAdmin,
            "Admin waitlist tools: send an offer, remove, reorder, and demand per Saturday.",
            "Gestion de la liste d’attente : envoyer une offre, retirer, réordonner et voir la demande par samedi.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.PromoReferralReports,
            "Promo usage and discount totals, referral code controls (active, max uses), credits granted and spent.",
            "Utilisation des promos et rabais accordés, contrôle des codes de parrainage (actif, utilisations max), crédits accordés et utilisés.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.VolunteerRoles,
            "Volunteer staff roles (court captain, treasurer) with limited admin access.",
            "Rôles bénévoles (capitaine de terrain, trésorier) avec un accès admin limité.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.SeasonScheduleWizard,
            "Create a season and every session for it in one step: session days, times, spots, drop-in price and gym.",
            "Créer une saison et toutes ses séances d'un coup : jours, heures, places, prix à la séance et gymnase.",
            IsPublic: false),
        new FeatureFlagDefinition(FeatureFlagKeys.SeasonsPageRedesign,
            "Redesigned seasons page: the season open now gets a hero with the club mark, the others become compact rows.",
            "Page des saisons repensée : la saison en cours est mise en vedette avec l'écusson du club, les autres deviennent des rangées compactes.",
            IsPublic: false),
    };
}
